musterkarten = {
    2: {
        "TypeOfDocument": "ID",
        "IssuingState": "D",
        "DateOfExpiry": "20291031",
        "GivenNames": "ANDRÈ",
        "FamilyNames": "MUSTERMANN",
        "NomDePlume": "",
        "AcademicTitle": "",
        "DateOfBirth": "19810617",
        "PlaceOfBirth": "FRANKFURT (ODER)",
        "Nationality": "",
        "Sex": "M",
        "BirthName": "",
        "DateOfIssuance": "20191101",
        "Street": "EHM-WELK-STRAẞE 33",
        "City": "LÜBBENAU/SPREEWALD",
        "Country": "D",
        "Zipcode": "03222"
    }, 3: {
        "TypeOfDocument": "ID",
        "IssuingState": "D",
        "DateOfExpiry": "20291031",
        "GivenNames": "JOHANNA EDELTRAUD LISBETH",
        "FamilyNames": "MUSTERMANN",
        "NomDePlume": "ORDENSSCHWESTER JOHANNA",
        "AcademicTitle": "DR.",
        "DateOfBirth": "19280421",
        "PlaceOfBirth": "MÜNCHEN",
        "Nationality": "D",
        "Sex": "M",
        "BirthName": "VON MÜLLER-SCHWARZENBERG",
        "DateOfIssuance": "20191101",
        "Street": "BOUCHÉSTR. 68A",
        "City": "BERLIN",
        "Country": "D",
        "Zipcode": "12059"
    },

    4: {
        "TypeOfDocument": "ID",
        "IssuingState": "D",
        "DateOfExpiry": "20291031",
        "GivenNames": "---",
        "FamilyNames": "ĆOSIĆ",
        "NomDePlume": "",
        "AcademicTitle": "",
        "DateOfBirth": "199409XX",
        "PlaceOfBirth": "PRIŠTINA",
        "Nationality": "D",
        "Sex": "M",
        "BirthName": "",
        "DateOfIssuance": "20191101",
        "Street": "F4 14-15",
        "City": "MANNHEIM",
        "Country": "D",
        "Zipcode": "68159"
    },

    5: {
        "TypeOfDocument": "ID",
        "IssuingState": "D",
        "DateOfExpiry": "20291031",
        "GivenNames": "AĞÇA",
        "FamilyNames": "ÖZM̂EN",
        "NomDePlume": "",
        "AcademicTitle": "",
        "DateOfBirth": "1989XXXX",
        "PlaceOfBirth": "DESSAU-ROẞLAU",
        "Nationality": "D",
        "Sex": "F",
        "BirthName": "",
        "DateOfIssuance": "20191101",
        "Street": "GROẞENHAINER STR. 133/135",
        "City": "DRESDEN",
        "Country": "D",
        "Zipcode": "01229"
    },

    7: {
        "TypeOfDocument": "ID",
        "IssuingState": "D",
        "DateOfExpiry": "20291031",
        "GivenNames": "ANNEKATHRIN",
        "FamilyNames": "LERCH",
        "NomDePlume": "",
        "AcademicTitle": "",
        "DateOfBirth": "19760705",
        "PlaceOfBirth": "BAD KÖNIGSHOFEN I. GRABFELD",
        "Nationality": "D",
        "Sex": "F",
        "BirthName": "BJØRNSON",
        "DateOfIssuance": "20191101",
        "Street": "",
        "City": "HALLE (SAALE)",
        "Country": "D",
        "Zipcode": "06108"
    },

    8: {
        "TypeOfDocument": "ID",
        "IssuingState": "D",
        "DateOfExpiry": "20291031",
        "GivenNames": "KARL",
        "FamilyNames": "HILLEBRANDT",
        "NomDePlume": "GRAF V. LÝSKY",
        "AcademicTitle": "DR.HC.",
        "DateOfBirth": "19520617",
        "PlaceOfBirth": "TRIER",
        "Nationality": "D",
        "Sex": "F",
        "BirthName": "missing",
        "DateOfIssuance": "20191101",
        "Street": "",
        "City": "",
        "Country": "",
        "Zipcode": ""
    },

    9: {
        "TypeOfDocument": "ID",
        "IssuingState": "D",
        "DateOfExpiry": "20251031",
        "GivenNames": "LILLY",
        "FamilyNames": "SCHUSTER",
        "NomDePlume": "",
        "AcademicTitle": "DR.HC.",
        "DateOfBirth": "20100330",
        "PlaceOfBirth": "MÜHLHAUSEN/THÜRINGEN",
        "Nationality": "D",
        "Sex": "F",
        "BirthName": "",
        "DateOfIssuance": "20191101",
        "Street": "MARIENSTRAẞE 144",
        "City": "EISENACH",
        "Country": "D",
        "Zipcode": "99817"
    },

    10: {
        "TypeOfDocument": "ID",
        "IssuingState": "D",
        "DateOfExpiry": "20291031",
        "GivenNames": "GHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGH",
        "FamilyNames": "CDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCD",
        "NomDePlume": "STSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTSTST",
        "AcademicTitle": "ABABABABABABABABABABABABABABABABABABABAB",
        "DateOfBirth": "18990502",
        "PlaceOfBirth": "IJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJIJ",
        "Nationality": "D",
        "Sex": "M",
        "BirthName": "EFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFE",
        "DateOfIssuance": "20191101",
        "Street": "OPOPOPOPOPOPOPOPOPOPOPOPOPOPOPOPOPOPOPOPOPOPOPOPOP",
        "City": "MNMNMNMNMNMNMNMNMNMNMNMNMNMNMNMNMNMNMNMNMNMN",
        "Country": "D",
        "Zipcode": "12345"
    }

}
